# Generated by Django 4.0.5 on 2022-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_uno', models.CharField(max_length=30)),
                ('nombre_dos', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('problematicas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Soporte_onsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_uno', models.CharField(max_length=30)),
                ('nombre_dos', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('problematicas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sw_de_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_uno', models.CharField(max_length=30)),
                ('nombre_dos', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('problematicas', models.CharField(max_length=30)),
            ],
        ),
    ]
