# Generated by Django 4.0.5 on 2022-07-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0003_mda_mda_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problematicas_sectores',
            options={'verbose_name_plural': 'Problematicas_sectores'},
        ),
    ]
