# Generated by Django 4.0.5 on 2022-07-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0004_alter_problematicas_sectores_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mda_admin',
            new_name='mda_admin_usuario',
        ),
        migrations.RenameModel(
            old_name='mda',
            new_name='mda_usuario',
        ),
    ]
