# Generated by Django 4.0.5 on 2022-07-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0007_rename_blog_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blog'},
        ),
    ]
