# Generated by Django 4.0.5 on 2022-07-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SoporteHAWebapp', '0008_alter_blogs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mda_admin_usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
