# Generated by Django 4.0.5 on 2022-07-25 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0011_rename_fecha_viaje_publicaciones_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
