# Generated by Django 4.0.5 on 2022-07-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0013_crearsectores_delete_problematicas_sectores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
