# Generated by Django 4.0.5 on 2022-07-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0015_remove_publicaciones_imagen_imagenespublicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImagenesPublicaciones',
        ),
    ]
