# Generated by Django 4.0.5 on 2022-08-01 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0016_publicaciones_imagen_delete_imagenespublicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPublicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SoporteHAWebapp.publicaciones')),
            ],
        ),
    ]
