# Generated by Django 4.0.5 on 2022-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoporteHAWebapp', '0017_imagespublicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagenone',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagenthree',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagentwo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImagesPublicaciones',
        ),
    ]
